name: Run MTS Bank tests

env:
  OS: ubuntu-latest

on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Скачивание Selenoid"
        run: curl -s https://aerokube.com/cm/bash | bash

      - name: "Запуск Selenoid"
        run: chmod +x ./cm | ./cm selenoid start --browsers 'chrome' --last-versions 1

      - name: "Доступ к workflow репозитория"
        uses: actions/checkout@v3

      - name: "Установка Java 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Запуск тестов"
        run: mvn clean test
        continue-on-error: true

      - name: "Генерация Allure-отчета"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: target/allure-results
          allure_report: target/allure-report
          allure_history: target/allure-history

      - name: "Деплой Allure-отчета в ветку gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: target/allure-history